# Generated by Django 4.0.6 on 2022-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='start_sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
            },
        ),
    ]
