# Generated by Django 4.0.6 on 2022-08-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteAlb', '0002_start_sim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start_sim',
            old_name='data_time',
            new_name='is_started',
        ),
    ]
