# Generated by Django 4.0.6 on 2022-08-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAlb', '0003_rename_data_time_start_sim_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_sim',
            name='userSim',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='start_sim',
            name='version',
            field=models.CharField(default='version', max_length=100),
        ),
    ]
