# Generated by Django 4.0.6 on 2022-08-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteAlb', '0004_start_sim_usersim_start_sim_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='start_sim',
        ),
    ]
