# Generated by Django 4.0.6 on 2022-08-29 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAlb', '0005_delete_start_sim'),
    ]

    operations = [
        migrations.CreateModel(
            name='versSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('is_started', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 15, 51, 40, 864038))),
                ('version', models.CharField(max_length=2)),
            ],
        ),
    ]
